#!/usr/bin/env python

# Copyright 2021 ipydrawio contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import shutil
import subprocess
import sys
from pathlib import Path

SETTINGS = Path(sys.prefix) / "share/jupyter/lab/settings"
SETTINGS.mkdir(parents=True, exist_ok=True)


def doit(*args):
    return subprocess.call(["doit", *args])


doit("list", "--all", "--status")
doit("-n4")
doit("list", "--all", "--status")

shutil.copy2(".binder/overrides.json", SETTINGS / "overrides.json")
shutil.copy2(".binder/jupyter_notebook_config.json", "jupyter_notebook_config.json")

sys.exit(doit())
