#!/usr/bin/env python
from pathlib import Path
import subprocess
import sys
import shutil

doit = lambda *args: subprocess.call(["doit", *args])

doit("list", "--all", "--status")
doit("-n4")
doit("list", "--all", "--status")

SETTINGS = Path(sys.prefix) / "share/jupyter/lab/settings"
SETTINGS.mkdir(parents=True, exist_ok=True)

shutil.copy2(".binder/overrides.json", SETTINGS / "overrides.json")
shutil.copy2(
    ".binder/jupyter_notebook_config.json",
    "jupyter_notebook_config.json"
)

sys.exit(doit())
